### ISSUE TITLE
[BUG] Crash on startup due to biometric authentication

### ISSUE THREAD

**Issue by xdevs23** [zeapo/Android-Password-Store#1044]
**Describe the bug**
When starting the app, it crashes immediately.
This has been happening for 2-3 days (that's as precise as I can tell)

**To Reproduce**
1. Enable biometric authentication (i. e. fingerprint)
2. Close app
3. Start app
4. It crashes

**Expected behavior**
App does not crash.

**Screenshots**
No screenshots, it just crashes when starting the app.

**Device information (please complete the following information):**
 - Device: OnePlus 5
 - OS: halogenOS 10 custom ROM (AOSP 10 r41)
 - App version 1.12.0-free from https://dl.msfjarvis.dev/APS/aps-free_1.12.0-SNAPSHOT-free.apk (Installed on 2020-08-23 ~08:45 UTC)

**Additional context**
Stack trace:
```
time: 1598172492705
msg: java.lang.IllegalArgumentException: Negative text must be set and non-empty.
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.msfjarvis.aps/com.zeapo.pwdstore.LaunchActivity}: java.lang.IllegalArgumentException: Negative text must be set and non-empty.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
Caused by: java.lang.IllegalArgumentException: Negative text must be set and non-empty.
	at com.zeapo.pwdstore.utils.BiometricAuthenticator.authenticate$default(BiometricAuthenticator.kt:199)
	at com.zeapo.pwdstore.LaunchActivity.onCreate(LaunchActivity.kt:4)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```

**Comment by msfjarvis** [comment]
Seems to still be broken on API 29...

**Comment by richanshah** [comment]
I didn't understand solution can anyone be more specific?

**Comment by msfjarvis** [comment]
> I didn't understand solution can anyone be more specific?

~~It's fixed in the app, there's no solution to be sought.~~ I thought you asked from a user perspective, my apologies. The fix in the app was to first allow biometrics again which I had accidentally switched to be device credentials only, then to allow weak biometrics which are present on older devices that lack the secure hardware components for strong biometrics.
