### ISSUE TITLE
Upgraded Password-Store from 1.2.0.23 to 1.2.0.24 from FDroid Causes Immediate Crash on Excute

### ISSUE THREAD

**Issue by ajstein** [zeapo/Android-Password-Store#109]
I tried clearing data and starting fresh, but after multiple downgrades and upgrades, 1.2.0.24 crashes immediately on execution when I press it on the home screen, running Android 5.1.1 (CyanogenMod 12.1-20150721-NIGHTLY-shamu) on my Nexus 6.

CatLog filtered to PASS for logcat only shows this.

```
07-25 02:05:33.673 I/ActivityManager(20182): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zeapo.pwdstore/.PasswordStore bnds=[861,1267][1143,1653] (has extras)} from uid 10023 on display 0
07-25 02:05:33.680 V/WindowManager(20182): addAppToken: AppWindowToken{35673428 token=Token{2bf7f24b ActivityRecord{2e8171a u0 com.zeapo.pwdstore/.PasswordStore t1765}}} to stack=1 task=1765 at 0
07-25 02:05:33.780 I/ActivityManager(20182): Start proc 29219:com.zeapo.pwdstore/u0a161 for activity com.zeapo.pwdstore/.PasswordStore
07-25 02:05:34.046 D/PASS    (29219): Check, dir: /data/data/com.zeapo.pwdstore/files/store
07-25 02:05:34.088 V/WindowManager(20182): Adding window Window{fd77996 u0 com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore} at 8 of 15 (before Window{269c10be u0 Starting com.zeapo.pwdstore})
07-25 02:05:34.151 W/SupportMenuInflater(29219): 	at com.zeapo.pwdstore.PasswordStore.onCreateOptionsMenu(Unknown Source)
07-25 02:05:34.153 E/AndroidRuntime(29219): 	at com.zeapo.pwdstore.PasswordStore.onCreateOptionsMenu(Unknown Source)
07-25 02:05:34.155 W/ActivityManager(20182):   Force finishing activity 1 com.zeapo.pwdstore/.PasswordStore
07-25 02:05:34.464 I/WindowManager(20182): Screenshot max retries 4 of Token{2bf7f24b ActivityRecord{2e8171a u0 com.zeapo.pwdstore/.PasswordStore t1765 f}} appWin=Window{269c10be u0 Starting com.zeapo.pwdstore} drawState=4
07-25 02:05:34.966 W/ActivityManager(20182): Activity pause timeout for ActivityRecord{2e8171a u0 com.zeapo.pwdstore/.PasswordStore t1765 f}
07-25 02:05:36.210 I/WindowState(20182): WIN DEATH: Window{fd77996 u0 com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}
```

Please let me know what I can do to provide more info and further troubleshoot.

**Comment by wongma7** [comment]
This should be fixed in 1.2.0.26. Unfortunately something is keeping the fdroid repo from updating... https://gitlab.com/fdroid/fdroiddata/issues/271

**Comment by wongma7** [comment]
1.2.0.26 appears to be out now. Please give it a try, I'll close this for now

**Comment by ajstein** [comment]
Excellent, @wongma7.  Thanks for your prompt help.  Download and will pull data from a backup, or start fresh when free, and see that it works.  But I did not get an immediate crash this time, so best I leave it closed.
