### ISSUE TITLE
Password deletion raises IOB exception

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#115]
```
java.lang.IndexOutOfBoundsException: Invalid index 3, size is 1
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.zeapo.pwdstore.PasswordStore.deletePassword(PasswordStore.java:362)
       at com.zeapo.pwdstore.utils.PasswordRecyclerAdapter$3.onActionItemClicked(PasswordRecyclerAdapter.java:149)
       at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onActionItemClicked(AppCompatDelegateImplV7.java:1510)
       at android.support.v7.internal.app.WindowDecorActionBar$ActionModeImpl.onMenuItemSelected(WindowDecorActionBar.java:1088)
       at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
       at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
       at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
       at android.view.View.performClick(View.java:4780)
       at android.view.View$PerformClick.run(View.java:19866)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by wongma7** [comment]
Oops, I forgot fix is a keyword, the commit was just an attempt. Since I cannot replicate it, I am not totally sure if it is fixed. Can you check?

Before, I relied on the order of the dialogs popping up.

**Comment by wongma7** [comment]
Btw I broke something terribly. I ought to stop using the Android Studio gui...fixing it now
