### ISSUE TITLE
ssh clone not working

### ISSUE THREAD

**Issue by brightdroid** [zeapo/Android-Password-Store#133]
When I'll try to use ssh, the server did not even see a ssh-login!? Why?

The App shows no error, just a blank UI...
---
```
V/WindowManager(  753): addAppToken: AppWindowToken{350a9448 token=Token{37ca3eeb ActivityRecord{18d7323a u0 com.zeapo.pwdstore/.git.GitActivity t11566}}} to stack=1 task=11566 at 1
W/System.err(15138): java.lang.ArrayIndexOutOfBoundsException: length=457; index=457
W/System.err(15138):    at com.jcraft.jsch.Buffer.getByte(Buffer.java:142)
W/System.err(15138):    at com.jcraft.jsch.Buffer.getShort(Buffer.java:137)
W/System.err(15138):    at com.jcraft.jsch.Buffer.getInt(Buffer.java:122)
W/System.err(15138):    at com.jcraft.jsch.Buffer.getBytes(Buffer.java:229)
W/System.err(15138):    at com.jcraft.jsch.KeyPairDSA.fromSSHAgent(KeyPairDSA.java:296)
W/System.err(15138):    at com.jcraft.jsch.KeyPair.load(KeyPair.java:598)
W/System.err(15138):    at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
W/System.err(15138):    at com.jcraft.jsch.KeyPair.load(KeyPair.java:532)
W/System.err(15138):    at com.zeapo.pwdstore.git.GitOperation.executeAfterAuthentication(GitOperation.java:139)
W/System.err(15138):    at com.zeapo.pwdstore.git.GitActivity.syncRepository(GitActivity.java:581)
W/System.err(15138):    at com.zeapo.pwdstore.git.GitActivity.onCreate(GitActivity.java:269)
W/System.err(15138):    at android.app.Activity.performCreate(Activity.java:5990)
W/System.err(15138):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
W/System.err(15138):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
W/System.err(15138):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
W/System.err(15138):    at android.app.ActivityThread.access$800(ActivityThread.java:151)
W/System.err(15138):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
W/System.err(15138):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(15138):    at android.os.Looper.loop(Looper.java:135)
W/System.err(15138):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err(15138):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15138):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(15138):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err(15138):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
V/WindowManager(  753): Adding window Window{138bdec7 u0 com.zeapo.pwdstore/com.zeapo.pwdstore.git.GitActivity} at 15 of 23 (after Window{9a5312e u0 PopupWindow:333ef143 EXITING})
I/ActivityManager(  753): Displayed com.zeapo.pwdstore/.git.GitActivity: +95ms
```

**Comment by wongma7** [comment]
Can you share info about the key so I can generate a similar one to test? Length, is it dsa, is it encrypted w/ passphrase. I think jsch has trouble loading it but oddly doesn't detect the key as invalid (would have thrown exception)?

**Comment by chaosworld** [comment]
SSH to git server is not working. 2048 length, no prompt on which type RSA or DSA, pls have a check.

**Comment by brightdroid** [comment]
Oh my fault, gitlab ignores the sshd_config "AuthorizedKeysFile" and stores it's keys in ~git/.ssh/...

**Comment by chaosworld** [comment]
Its working?

**Comment by brightdroid** [comment]
Yes, with the generated key from the app and the changed sshd_config "AuthorizedKeysFile" (back to default).

**Comment by chaosworld** [comment]
But I'm not using gitlab for git repo. I'm using normal ssh login and there's no AuthorizedKeysFile. You mean /etc/sshd_config file?

**Comment by brightdroid** [comment]
Yes, the sshd_config (location depends on your linux distribution)

I had this in my config:
```
AuthorizedKeysFile     /etc/ssh/authorized_keys/%u
```
Which does not work, cause gitlab assumes this:
```
AuthorizedKeysFile      %h/.ssh/authorized_keys
```
So I think, this wouldn't help you, but you could try if using the key from the app on a linux client does work.

**Comment by chaosworld** [comment]
Yep. Thanks for the detail. I'll check if it work.

**Comment by chaosworld** [comment]
Thanks, I solved the problem after I google I'm not config git repo properly.

Here's the process of creating a git repo from https://www.eclipse.org/forums/index.php/t/262790/
<code bash>
git init -bare passwordstore-repo
cd passwordstore-repo
git config branch.master.remote origin
git config branch.master.merge refs/heads/
</code>
