### ISSUE TITLE
Crash in AutoFill

### ISSUE THREAD

**Issue by zeapo** [zeapo/Android-Password-Store#138]
Noticed on PlayStore, version `1.2.0.34`:
```text
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@2fcaa65 -- permission denied for this window type
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
       at android.app.Dialog.show(Dialog.java:319)
       at com.zeapo.pwdstore.autofill.AutofillService.onAccessibilityEvent(AutofillService.java:181)
       at android.accessibilityservice.AccessibilityService$1.onAccessibilityEvent(AccessibilityService.java:658)
       at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:751)
       at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wongma7** [comment]
This occurs if the user removes the 'Draw over other apps' permission from the app (now an official feature in Android M?), right? So I will figure out how to handle this (and other permissions being removed) gracefully.

**Comment by zeapo** [comment]
I see, that would be great to have.

**Comment by rfc1459** [comment]
81abb79 caused autofill to stop working altogether on Android M. Most likely, `ContextCompat.checkSelfPermission(this, Manifest.permission.SYSTEM_ALERT_WINDOW)` does not work as intended on M, given that developer docs say that [Settings.canDrawOverlays](https://developer.android.com/reference/android/provider/Settings.html#canDrawOverlays\(android.content.Context\)) should be used to check if the application has been (explicitly) granted the overlay permission.

**Comment by wongma7** [comment]
Sorry, I see, SYSTEM_ALERT_WINDOW is special; I was treating it like other permissions. Working on it now, I think it deserves a new version for M users...
