### ISSUE TITLE
[BUG] Autofill Service crash on the latest Twitter app

### ISSUE THREAD

**Issue by Skrilltrax** [zeapo/Android-Password-Store#1468]
**Describe the bug**
Autofill service crashes on Twitter's OTP text field. The crash happens just before the message notification comes in so ig it could be related to the message parsing feature. Attaching logs below so I or someone else can take a look at it.

**To Reproduce**
Login to the latest Twitter app.

**Expected behavior**
Autofill service should not crash.

**Screenshots**

**Device information (please complete the following information):**
 - Device: Poco F1
 - OS: Android 12 Beta 3 (Pixel 3XL System Image)
 - App version 1.13.4

**Additional context**
Crash Log
```
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: FATAL EXCEPTION: main
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: Process: dev.msfjarvis.aps, PID: 17311
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: java.lang.NullPointerException: it must not be null
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.github.androidpasswordstore.autofillparser.FormField.<init>(FormField.kt:46)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:13)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:29)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:29)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.github.androidpasswordstore.autofillparser.AutofillFormParser.<init>(AutofillFormParser.kt:14)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.zeapo.pwdstore.autofill.oreo.OreoAutofillService.onFillRequest(OreoAutofillService.kt:16)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.service.autofill.AutofillService$1$$ExternalSyntheticLambda0.accept(Unknown Source:8)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:307)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7829)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-23 21:35:09.112 10215 17311 17311 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:
```

**Comment by fmeum** [comment]
The line numbers in the log don't really match our source code. I'm trying to reproduce this bug myself now.

**Comment by fmeum** [comment]
Reproduces on `develop`:
```
java.lang.NullPointerException: it must not be null
at com.github.androidpasswordstore.autofillparser.FormField.<init>(FormField.kt:206)
at com.github.androidpasswordstore.autofillparser.FormField.<init>(FormField.kt:28)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:111)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:122)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode(AutofillFormParser.kt:122)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.visitFormNode$default(AutofillFormParser.kt:104)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.parseStructure(AutofillFormParser.kt:100)
at com.github.androidpasswordstore.autofillparser.AutofillFormParser.<init>(AutofillFormParser.kt:88)
at com.github.androidpasswordstore.autofillparser.FillableForm$Companion.parseAssistStructure(AutofillFormParser.kt:209)
at dev.msfjarvis.aps.util.services.OreoAutofillService.onFillRequest(OreoAutofillService.kt:88)
at android.service.autofill.AutofillService$1$$ExternalSyntheticLambda0.accept(Unknown Source:8)
at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:307)
at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7829)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
```

**Comment by fmeum** [comment]
@Skrilltrax Could you verify that https://github.com/android-password-store/Android-Password-Store/pull/1469 fixes the issue for you?

**Comment by Skrilltrax** [comment]
@fmeum just checked, it does fix the issue for me
