### ISSUE TITLE
[BUG] Debug build crashes

### ISSUE THREAD

**Issue by mimi89999** [zeapo/Android-Password-Store#1822]
### Describe the bug

Hello,
After building commit 1d6d14e6f710b74b08291e8e94c7810d3f2ccff9 with `./gradlew assembleFreeDebug` and installing it on my device, the build crashes with
```
04-06 13:52:44.206   992   992 E AndroidRuntime: FATAL EXCEPTION: main
04-06 13:52:44.206   992   992 E AndroidRuntime: Process: dev.msfjarvis.aps.debug, PID: 992
04-06 13:52:44.206   992   992 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application dev.msfjarvis.aps.debug.Application: java.lang.ClassNotFoundException: Didn't find class "dev.msfjarvis.aps.debug.Application" on path: DexPathList[[zip file "/data/app/~~rsbqErUlvdhzDvNN1u5BfA==/dev.msfjarvis.aps.debug-gIFsPItFpCqs5ailoAJZmg==/base.apk"],nativeLibraryDirectories=[/data/app/~~rsbqErUlvdhzDvNN1u5BfA==/dev.msfjarvis.aps.debug-gIFsPItFpCqs5ailoAJZmg==/lib/arm64, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1268)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-06 13:52:44.206   992   992 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "dev.msfjarvis.aps.debug.Application" on path: DexPathList[[zip file "/data/app/~~rsbqErUlvdhzDvNN1u5BfA==/dev.msfjarvis.aps.debug-gIFsPItFpCqs5ailoAJZmg==/base.apk"],nativeLibraryDirectories=[/data/app/~~rsbqErUlvdhzDvNN1u5BfA==/dev.msfjarvis.aps.debug-gIFsPItFpCqs5ailoAJZmg==/lib/arm64, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
04-06 13:52:44.206   992   992 E AndroidRuntime: 	... 9 more
```

I inspected the apk and indeed, in the manifest contains references to `dev.msfjarvis.aps.debug`, but there are only `dev.msfjarvis.aps` classes in the apk.

**Comment by msfjarvis** [comment]
Can you revert 2320201f8955 and test if it fixes the issue?
