### ISSUE TITLE
[BUG] GitHub clone with SSH Timeout

### ISSUE THREAD

**Issue by 1995parham** [zeapo/Android-Password-Store#2033]
### Describe the bug

I use the latest snapshot version but when I want to clone a new repository with SSH key, it gives me timeout without any further logs. I don't have any issue with the latest stable release.

### Steps to reproduce

1. Go into app
2. clone repository
3. use ssh keys
4. git operation timeout

### Expected behavior

successful clone

### Device information

- Device: Samsung Galaxy Tab s6 lite WiFi
- OS: Lineageos 19.1
- App version Latest release for APS from revision https://github.com/android-password-store/Android-Password-Store/commit/23721bf0375b9c61ff874fe36fb042065d788391

**Comment by msfjarvis** [comment]
You can enable debug logging in the app at `Settings > Misc > Debug logging`. Then you retry using SSH and capture the logs using ADB and attach them here.

**Comment by 1995parham** [comment]
Thanks for your advice. I have attached the logs.

```
07-26 19:24:28.161 29238 29238 D PasswordStore: net.schmizz.sshj.transport.TransportException: Timeout expired
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlin.text.Regex$Companion.chain(SourceFile:16)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at net.schmizz.concurrent.Promise.retrieve(SourceFile:79)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at net.schmizz.concurrent.Event.await(Unknown Source:2)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at net.schmizz.sshj.transport.KeyExchanger.startKex(SourceFile:121)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at net.schmizz.sshj.SSHClient.onConnect(SourceFile:429)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at app.passwordstore.util.git.sshj.SshjSessionFactory.getSession(SourceFile:278)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.transport.SshTransport.getSession(SourceFile:31)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(SourceFile:2)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(Unknown Source:2)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.pgpainless.policy.Policy.executeImp(SourceFile:10)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.transport.Transport.fetch(SourceFile:129)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.api.FetchCommand.call(SourceFile:17)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at org.eclipse.jgit.api.PullCommand.call(SourceFile:34)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at app.passwordstore.util.git.GitCommandExecutor$execute$2$result$1.invokeSuspend(Unknown Source:7)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:111)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:12)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
07-26 19:24:28.161 29238 29238 D PasswordStore: Caused by: java.util.concurrent.TimeoutException: Timeout expired
07-26 19:24:28.161 29238 29238 D PasswordStore: 	at net.schmizz.concurrent.Promise.retrieve(SourceFile:74)
07-26 19:24:28.161 29238 29238 D PasswordStore: 	... 17 more
```

**Comment by msfjarvis** [comment]
This doesn't look like a problem with the app, you might want to double check your in-app and server configurations.

**Comment by 1995parham** [comment]
Sure, is there any way for checking the request URL?

**Comment by msfjarvis** [comment]
> Sure, is there any way for checking the request URL?

The debug logs should contain a lot of verbose logging from SSHJ, the SSH library we use. You can look through those to see how the app is interacting with the server.

**Comment by 1995parham** [comment]
Thanks for @msfjarvis for your support. The problem is with my network, I think.
