### ISSUE TITLE
Crash when password folder title is too long

### ISSUE THREAD

**Issue by danielvandenberg95** [zeapo/Android-Password-Store#207]
I've got a nested structure as such:

/home/PCs/remoteControl/ChromeRemoteDesktop/myPass

I can get into the folder "remoteControl", but tapping the folder "ChromeRemoteDesktop" crashes the application, leaving no error message or anything. If I hold my phone horizontally it works just fine though. As such, I think this has to do with the full title of the current path not fitting in the textfield.

**Comment by danielvandenberg95** [comment]
FATAL EXCEPTION: main
Process: com.zeapo.pwdstore, PID: 7834
java.lang.ArrayIndexOutOfBoundsException: length=45; index=-1
  at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:667)
  at android.text.StaticLayout.out(StaticLayout.java:631)
  at android.text.StaticLayout.generate(StaticLayout.java:423)
  at android.text.StaticLayout.<init>(StaticLayout.java:140)
  at android.widget.TextView.makeSingleLayout(TextView.java:6449)
  at android.widget.TextView.makeNewLayout(TextView.java:6306)
  at android.widget.TextView.onMeasure(TextView.java:6663)
  at android.view.View.measure(View.java:17586)
  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
  at android.view.View.measure(View.java:17586)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5543)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
  at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
  at android.view.View.measure(View.java:17586)
  at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:7487)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1416)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
  at android.view.View.layout(View.java:15715)
  at android.view.ViewGroup.layout(ViewGroup.java:5046)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2097)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1069)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5915)
at android.view.Choreographer$CallbackRecord.run(Choreographer.j

**Comment by zeapo** [comment]
Thanks for the report.

**Comment by danielvandenberg95** [comment]
Should be fixed by https://github.com/zeapo/Android-Password-Store/pull/208
