### ISSUE TITLE
[FEATURE] Add URL level autofill support for Vivaldi browser

### ISSUE THREAD

**Issue by kensmith** [zeapo/Android-Password-Store#2165]
### Describe the bug

Autofill autopopulates the URL correctly in native apps and in Chrome but doesn't seem to work in Vivaldi. 
![example-chrome-working-as-expected](https://user-images.githubusercontent.com/348396/194163575-381bdbe0-a1ad-470a-a43a-95462dfad44f.png)
![example-vivaldi-not-working-as-expected](https://user-images.githubusercontent.com/348396/194163576-939b64dd-a8db-4ee6-b173-1cab9532c628.png)

Deleting "Vivaldi Browser" after clicking "Search in store..." does work and once selected, it does autofill the fields correctly.

### Steps to reproduce

1. Go to any site for which there is a password in APS
2. Click on the login or password field
3. See that the autofill popup wants to search for "Vivaldi Browser" instead of the site URL.

### Expected behavior

The autofill popup should default to searching for the site URL and not the string "Vivaldi Browser"

### Screenshots

Included in description above.

### Device information

- Device: Google Pixel 6
- OS: Android 13, build number TP1A.220624.021
- App version 1.13.5 (FDroid, nonfree)

**Comment by msfjarvis** [comment]
APS uses an internal allowlist of browsers known to have functional Autofill implementations before exposing full capabilities, which is why there's no URL-level autofill there.

I'll investigate Vivaldi's feature set and include it in the list.

**Comment by kensmith** [comment]
Thanks @msfjarvis, Vivaldi is based on Chrome so I suspect the same APIs that work for Chrome will work for Vivaldi.

**Comment by kensmith** [comment]
Thank you for shipping the change so quickly! I just installed the latest snapshot and it seems not to work in Vivaldi. The popup simply does not appear. I tried in Chrome and received this stacktrace:

```
java.lang.IllegalStateException: All presentations are null.
  at android.service.autofill.Presentations.onConstructed(Presentations.java:85)
  at android.service.autofill.Presentations.<init>(Presentations.java:119)
  at android.service.autofill.Presentations$Builder.build(Presentations.java:250)
  at app.passwordstore.util.autofill.Api30AutofillResponseBuilder.makeIntentDataset(SourceFile:26)
  at app.passwordstore.util.autofill.Api30AutofillResponseBuilder.makeFillResponse(SourceFile:267)
  at app.passwordstore.util.services.OreoAutofillService.onFillRequest(SourceFile:423)
  at android.service.autofill.AutofillService$1$$ExternalSyntheticLambda4.accept(Unknown Source:8)
  at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:310)
  at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
  at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by msfjarvis** [comment]
This works fine for me on Android 13 🤔 

What keyboard are you using?

**Comment by kensmith** [comment]
The built in Gboard that ships with Android 13.

**Comment by msfjarvis** [comment]
> The built in Gboard that ships with Android 13.

Guess that's not the problem then. I'll investigate and get back if I need more information.

**Comment by kensmith** [comment]
I'm happy to help you test this. Just drop a note when I should install the latest snapshot.

**Comment by kensmith** [comment]
Would it be possible to reopen this issue for tracking? I believe it is still an issue. I certainly is in 1.13.5 from Fdroid.

**Comment by msfjarvis** [comment]
> Would it be possible to reopen this issue for tracking? I believe it is still an issue. I certainly is in 1.13.5 from Fdroid.

#2290
