### ISSUE TITLE
[BUG] Autofill occasionally crashes with "All presentations are null"

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#2290]
### Describe the bug

```
java.lang.IllegalStateException: All presentations are null.
  at android.service.autofill.Presentations.onConstructed(Presentations.java:85)
  at android.service.autofill.Presentations.<init>(Presentations.java:119)
  at android.service.autofill.Presentations$Builder.build(Presentations.java:250)
  at app.passwordstore.util.autofill.Api30AutofillResponseBuilder.makeIntentDataset(SourceFile:26)
  at app.passwordstore.util.autofill.Api30AutofillResponseBuilder.makeFillResponse(SourceFile:267)
  at app.passwordstore.util.services.OreoAutofillService.onFillRequest(SourceFile:423)
  at android.service.autofill.AutofillService$1$$ExternalSyntheticLambda4.accept(Unknown Source:8)
  at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:310)
  at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
  at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
  at android.os.Handler.handleCallback(Handler.java:942)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  ```

### Steps to reproduce

There are no consistent steps for reproduction AFAICT.

### Expected behavior

Autofill presentations are filtered for nulls before being forwarded to the Autofill service

### Device information

- Device: Pixel 7
- OS: Android 13 QPR
- App version: 2.0.0-SNAPSHOT (521389db018deee2e7bd59efb14e2059a42f1cd9)

**Comment by kensmith** [comment]
Thanks for filing this :pray:
