### ISSUE TITLE
[BUG] Failed to parse identifiers from .gpg-id

### ISSUE THREAD

**Issue by alanorth** [zeapo/Android-Password-Store#2759]
### Describe the bug

Attempting to view any password in the application crashes the application with the following error:

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2023110900:user/release-keys
package: app.passwordstore:20000
process: app.passwordstore
processUptime: 4775 + 305 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: Failed to parse identifiers from .gpg-id: 
	at app.passwordstore.ui.crypto.BasePGPActivity.getPGPIdentifiers(Unknown Source:250)
	at app.passwordstore.ui.crypto.DecryptActivity.decrypt(Unknown Source:2)
	at app.passwordstore.ui.crypto.DecryptActivity$onCreate$3.invoke(Unknown Source:13)
	at app.passwordstore.ui.crypto.BasePGPActivity$requireKeysExist$1.invokeSuspend(Unknown Source:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:115)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@da18da3, Dispatchers.Main.immediate]
```

### Steps to reproduce

1. Open the application
2. Click on a password entry
3. Application crashes

### Expected behavior

Application should not crash.

### Device information

- Device: Google Pixel 4a
- OS: Android 13 (CopperheadOS)
- App version: 2.0.0-SNAPSHOT (around 62d3f4aca1399f276f0827ec932690c0dbf65848)

**Comment by msfjarvis** [comment]
If you're fine with your key ID being public it'd be very helpful to see your `.gpg-id` file.

**Comment by alanorth** [comment]
@msfjarvis my key ID is already public so I don't mind, but where is the `.gpg-id` file? I don't see it in my password store repo.

**Comment by msfjarvis** [comment]
> @msfjarvis my key ID is already public so I don't mind, but where is the `.gpg-id` file? I don't see it in my password store repo.

That's weird :/ It should exist at the root of the repository, like this https://github.com/android-password-store/pass-test/blob/main/.gpg-id

If it's definitely not there it probably needs to be created, in which case you can just create it as a plaintext file with your key ID written down as-is.

**Comment by alanorth** [comment]
Ah, I definitely don't have that file at the root. My repository was created in 2015 and I only ever used the `pass` client. I created the file with my key fingerprint and synced my repository and now I get a password popup. Thanks!
