### ISSUE TITLE
User Not Authenticated Error

### ISSUE THREAD

**Issue by MijikHna** [zeapo/Android-Password-Store#2979]
### Describe the bug

After updating to latest pre-release of 2.0.0 version, PasswordStore crashes with following error message:

```
03-31 20:47:02.763  8537  8569 D org.pgpainless.decryption_verification.OpenPgpMessageInputStream: Successfully decrypted data with key ....
03-31 20:47:02.764  8537  8569 D org.pgpainless.decryption_verification.OpenPgpMessageInputStream: Compressed Data Packet (ZIP) at depth 1 encountered
03-31 20:47:02.764  8537  8569 D org.pgpainless.decryption_verification.OpenPgpMessageInputStream: Literal Data Packet at depth 2 encountered
03-31 20:47:02.765  8537  8569 D org.pgpainless.decryption_verification.IntegrityProtectedInputStream: Integrity Protection check passed
03-31 20:47:02.853  1496  9267 E keymaster_worker: getAuthToken failed: -2
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: encountered a potentially transient KeyStore error, will wait and retry
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: android.security.keystore.UserNotAuthenticatedException: User not authenticated
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1346)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1388)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.init(Cipher.java:1143)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.init(Cipher.java:1084)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.encryptInternal(Unknown Source:20)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.encrypt(Unknown Source:0)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getAead(Unknown Source:64)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(Unknown Source:7)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(Unknown Source:44)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at androidx.security.crypto.EncryptedSharedPreferences.create(Unknown Source:71)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invokeSuspend(Unknown Source:51)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invoke(Unknown Source:12)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at logcat.ThrowablesKt.startUndispatchedOrReturn(Unknown Source:4)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at kotlin.TuplesKt.withContext(Unknown Source:73)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at app.passwordstore.data.crypto.PGPPassphraseCache.access$getPreferences(Unknown Source:68)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at app.passwordstore.data.crypto.PGPPassphraseCache$cachePassphrase$2.invokeSuspend(Unknown Source:30)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:66)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-31 20:47:02.859  8537  8569 W AndroidKeystoreAesGcm: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
03-31 20:47:02.921  1496  9267 E keymaster_worker: getAuthToken failed: -2
03-31 20:47:02.977  8537  8537 E AndroidRuntime: FATAL EXCEPTION: main
03-31 20:47:02.977  8537  8537 E AndroidRuntime: Process: app.passwordstore, PID: 8537
03-31 20:47:02.977  8537  8537 E AndroidRuntime: android.security.keystore.UserNotAuthenticatedException: User not authenticated
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1346)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1388)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1143)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1084)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.encryptInternal(Unknown Source:20)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.encrypt(Unknown Source:27)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getAead(Unknown Source:64)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(Unknown Source:7)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(Unknown Source:44)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at androidx.security.crypto.EncryptedSharedPreferences.create(Unknown Source:71)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invokeSuspend(Unknown Source:51)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invoke(Unknown Source:12)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at logcat.ThrowablesKt.startUndispatchedOrReturn(Unknown Source:4)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at kotlin.TuplesKt.withContext(Unknown Source:73)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache.access$getPreferences(Unknown Source:68)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$cachePassphrase$2.invokeSuspend(Unknown Source:30)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:66)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
03-31 20:47:02.977  8537  8537 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cb5d419, Dispatchers.Main]
```

I have used previous pre-release build which I have installed maybe 6 month ago and PasswordStore worked just fine.
I have already completely deleted PasswordStore and installed it from scratch, but the problem still persist.

### Steps to reproduce

1. Go to some password (for example **Github Password**)
2. Click on **Github password** to enter gpg password to encrypt **Github password**
4. See Error
    - App doesn't crash actually.
    - App opens next View the password and password related notes, but an error occurs directly.
    - App shows again previous view (Search Password View)

### Expected behavior

App should show *password and password details view* without the error.

### Device information

- Device: Moto G10
- OS: Android 11
- App version: 2.0.0 pre-release

### Additional context

Before the full re-installation the error also had this part before actual `User not authenctiated` error
```
03-31 19:21:45.825  9940  9940 E AndroidRuntime: java.security.KeyStoreException: the master key android-keystore://passphrase exists but is unusable
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewMasterKey(Unknown Source:48)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(Unknown Source:24)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at androidx.security.crypto.EncryptedSharedPreferences.create(Unknown Source:71)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invokeSuspend(Unknown Source:51)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$getPreferences$2.invoke(Unknown Source:12)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at logcat.ThrowablesKt.startUndispatchedOrReturn(Unknown Source:4)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at kotlin.TuplesKt.withContext(Unknown Source:73)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache.access$getPreferences(Unknown Source:68)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at app.passwordstore.data.crypto.PGPPassphraseCache$cachePassphrase$2.invokeSuspend(Unknown Source:30)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:66)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9c203db, Dispatchers.Main]
03-31 19:21:45.825  9940  9940 E AndroidRuntime: Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1346)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1388)
03-31 19:21:45.825  9940  9940 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
```

**Comment by msfjarvis** [comment]
This error should only happen if the biometric prompt somehow didn't show up when it was supposed to. Can you try disabling the passphrase cache feature and trying again? If it still fails, please grab another log.

**Comment by MijikHna** [comment]
Thank you. I have had passphrase disabled. But enabling it and disabling it again fixed it.

**Comment by MijikHna** [comment]
@msfjarvis I need to enable and disable `passphrase cache` each time I open the app. Is there a way to manually remove the cache of the app? I couldn't find the app folder on my device.

**Comment by msfjarvis** [comment]
Update to the latest snapshot, disabling the cache will drop all entries then.

**Comment by MijikHna** [comment]
Thank you again. Seems now to work properly.
