### ISSUE TITLE
[BUG] Wrong Password on GrapheneOS (No subkeys)

### ISSUE THREAD

**Issue by Vintodrimmer** [zeapo/Android-Password-Store#3185]
### Describe the bug

I'm unable to decrypt the keys. After entering the GPG password I get the "Wrong Password" prompt and nothing else.

Error looks very similar to [this issue](https://github.com/android-password-store/Android-Password-Store/issues/2846), but according to [this issue](https://github.com/android-password-store/Android-Password-Store/issues/2751) which the first one is a dupe of, they are using sub-keys and that's where the problem lies, while I'm not using any sub-keys or any additional commands when using my GPG key either with `pass` or `pass4ios`. Additionally, I don't get any errors when trying to create a new password, so I assume it's a different issue.

If I'm mistaken and it's the same issue, then I apologize for the inconvenience.

### Steps to reproduce

1. gpg --export-secret-keys myemail@address.com > private.asc
2. Import it into the APS
3. Try unlocking any existing or newly created password

### Expected behavior

Being able to use the GPG password to open the files.

### Device information

- Device: Google Pixel 9 Pro XL
- OS: GrapheneOS
- App version: Latest GitHub apk

### Additional context

Here's the error log:

```
--------- beginning of main
08-23 20:17:47.661 12588 12588 I p.passwordstore: Using CollectorTypeCMC GC.
08-23 20:17:47.664 12588 12588 E p.passwordstore: Not starting debugger since process cannot load the jdwp agent.
08-23 20:17:47.709 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.706 12588 12588 W app_process64: type=1400 audit(0.0:3751): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.718 12588 12588 W app_process64: type=1400 audit(0.0:3752): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.721 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.722 12588 12588 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10175 <<<<<<
08-23 20:17:47.722 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.718 12588 12588 W p.passwordstore: type=1400 audit(0.0:3753): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.722 12588 12588 W p.passwordstore: type=1400 audit(0.0:3754): avc:  denied  { read } for  name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=284 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.722 12588 12588 W p.passwordstore: type=1400 audit(0.0:3755): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.725 12588 12588 I AndroidRuntime: Using default boot image
08-23 20:17:47.725 12588 12588 I AndroidRuntime: Leaving lock profiling enabled
08-23 20:17:47.725 12588 12588 W libc    : Access denied finding property "odsign.verification.success"
08-23 20:17:47.725 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.726 12588 12588 E cutils-trace: Error opening trace file: No such file or directory (2)
08-23 20:17:47.722 12588 12588 W p.passwordstore: type=1400 audit(0.0:3756): avc:  denied  { getattr } for  path="/apex/apex-info-list.xml" dev="tmpfs" ino=81 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:apex_info_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.727 12588 12588 W app.passwordstore: ART APEX data files are untrusted.
08-23 20:17:47.727 12588 12588 I app.passwordstore: Using CollectorTypeCMC GC.
08-23 20:17:47.734 12588 12588 W p.passwordstore: type=1400 audit(0.0:3757): avc:  denied  { lock } for  path="/system/framework/arm64/boot.art" dev="dm-6" ino=1336 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.738 12588 12588 W p.passwordstore: type=1400 audit(0.0:3758): avc:  denied  { lock } for  path="/system/framework/arm64/boot-core-libart.art" dev="dm-6" ino=1270 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.738 12588 12588 W p.passwordstore: type=1400 audit(0.0:3759): avc:  denied  { lock } for  path="/system/framework/arm64/boot-okhttp.art" dev="dm-6" ino=1318 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.738 12588 12588 W p.passwordstore: type=1400 audit(0.0:3760): avc:  denied  { lock } for  path="/system/framework/arm64/boot-bouncycastle.art" dev="dm-6" ino=1258 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.738 12588 12588 W p.passwordstore: type=1400 audit(0.0:3761): avc:  denied  { lock } for  path="/system/framework/arm64/boot-apache-xml.art" dev="dm-6" ino=1252 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.738 12588 12588 W p.passwordstore: type=1400 audit(0.0:3762): avc:  denied  { lock } for  path="/system/framework/arm64/boot-framework.art" dev="dm-6" ino=1306 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.746 12588 12588 W p.passwordstore: type=1400 audit(0.0:3763): avc:  denied  { lock } for  path="/system/framework/arm64/boot-framework-graphics.art" dev="dm-6" ino=1288 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.746 12588 12588 W p.passwordstore: type=1400 audit(0.0:3764): avc:  denied  { lock } for  path="/system/framework/arm64/boot-framework-location.art" dev="dm-6" ino=1294 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.746 12588 12588 W p.passwordstore: type=1400 audit(0.0:3765): avc:  denied  { lock } for  path="/system/framework/arm64/boot-ext.art" dev="dm-6" ino=1276 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.746 12588 12588 W p.passwordstore: type=1400 audit(0.0:3766): avc:  denied  { lock } for  path="/system/framework/arm64/boot-telephony-common.art" dev="dm-6" ino=1324 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.746 12588 12588 W p.passwordstore: type=1400 audit(0.0:3767): avc:  denied  { lock } for  path="/system/framework/arm64/boot-voip-common.art" dev="dm-6" ino=1330 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.750 12588 12588 W p.passwordstore: type=1400 audit(0.0:3768): avc:  denied  { lock } for  path="/system/framework/arm64/boot-ims-common.art" dev="dm-6" ino=1312 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.750 12588 12588 W p.passwordstore: type=1400 audit(0.0:3769): avc:  denied  { lock } for  path="/system/framework/arm64/boot-framework-nfc.art" dev="dm-6" ino=1300 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.750 12588 12588 W p.passwordstore: type=1400 audit(0.0:3770): avc:  denied  { lock } for  path="/system/framework/arm64/boot-core-icu4j.art" dev="dm-6" ino=1264 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.754 12588 12588 W p.passwordstore: type=1400 audit(0.0:3771): avc:  denied  { lock } for  path="/system/framework/arm64/boot-framework-adservices.art" dev="dm-6" ino=1282 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.785 12588 12588 D nativeloader: InitDefaultPublicLibraries for_preload=1: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libicu.so:libicui18n.so:libicuuc.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativehelper.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
08-23 20:17:47.791 12588 12588 D nativeloader: Load libicu_jni.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-23 20:17:47.791 12588 12588 D app.passwordstore: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
08-23 20:17:47.791 12588 12588 D app.passwordstore: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt72l.dat
08-23 20:17:47.792 12588 12588 D nativeloader: Load libjavacore.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-23 20:17:47.793 12588 12588 D nativeloader: Load libopenjdk.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.product.name_for_attestation"
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.product.device_for_attestation"
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.product.manufacturer_for_attestation"
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.product.brand_for_attestation"
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.product.model_for_attestation"
08-23 20:17:47.811 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.812 12588 12588 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
08-23 20:17:47.812 12588 12588 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
08-23 20:17:47.812 12588 12588 D Zygote  : begin preload
08-23 20:17:47.812 12588 12588 I Zygote  : Calling ZygoteHooks.beginPreload()
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3772): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3773): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3774): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3775): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3776): avc:  denied  { read } for  name="u:object_r:build_attestation_prop:s0" dev="tmpfs" ino=111 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:build_attestation_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.806 12588 12588 W main    : type=1400 audit(0.0:3777): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.823 12588 12588 I Zygote  : Preloading shared libraries...
08-23 20:17:47.823 12588 12588 D nativeloader: Load libandroid.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-23 20:17:47.824 12588 12588 D nativeloader: Load libjnigraphics.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-23 20:17:47.824 12588 12588 D nativeloader: Load libcompiler_rt.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-23 20:17:47.824 12588 12588 E app.passwordstore: Unable to find pattern file or unable to map it for am
08-23 20:17:47.825 12588 12588 I Zygote  : Called ZygoteHooks.endPreload()
08-23 20:17:47.826 12588 12588 D nativeloader: Load libjavacrypto.so using APEX ns com_android_conscrypt for caller /apex/com.android.conscrypt/javalib/conscrypt.jar: ok
08-23 20:17:47.830 12588 12588 I Zygote  : Installed AndroidKeyStoreProvider in 6ms.
08-23 20:17:47.830 12588 12588 D Zygote  : end preload
08-23 20:17:47.835 12588 12614 W libc    : Access denied finding property "qemu.sf.lcd_density"
08-23 20:17:47.835 12588 12614 W libc    : Access denied finding property "qemu.sf.lcd_density"
08-23 20:17:47.830 12588 12588 W binder:12588_2: type=1400 audit(0.0:3778): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=308 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.830 12588 12588 W binder:12588_2: type=1400 audit(0.0:3779): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=308 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.843 12588 12588 D nativeloader: Load libstats_jni.so using APEX ns com_android_os_statsd for caller /apex/com.android.os.statsd/javalib/framework-statsd.jar: ok
08-23 20:17:47.843 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10175; state: ENABLED
08-23 20:17:47.843 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10175; state: ENABLED
08-23 20:17:47.849 12588 12588 I Typeface: Preloading /system/fonts/Roboto-Regular.ttf
08-23 20:17:47.849 12588 12588 I Typeface: Preloading /system/fonts/RobotoStatic-Regular.ttf
08-23 20:17:47.852 12588 12588 I SystemFonts: Loading font config from /system/etc/fonts.xml
08-23 20:17:47.853 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10175; state: ENABLED
08-23 20:17:47.868 12588 12588 D nativeloader: InitApexLibraries:
08-23 20:17:47.868 12588 12588 D nativeloader:   com_android_art: libnativehelper.so
08-23 20:17:47.868 12588 12588 D nativeloader:   com_android_i18n: libicui18n.so:libicuuc.so:libicu.so
08-23 20:17:47.868 12588 12588 D nativeloader:   com_android_neuralnetworks: libneuralnetworks.so
08-23 20:17:47.868 12588 12588 D nativeloader: InitDefaultPublicLibraries for_preload=0: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libclang_rt.hwasan-aarch64-android.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
08-23 20:17:47.868 12588 12588 D nativeloader: Configuring clns-1 for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~Nj98FDzFGKab8q44iEjhpw==/app.passwordstore-9DuVAg9KTTFMzwf627ZrJA==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/app.passwordstore
08-23 20:17:47.868 12588 12588 D nativeloader: InitExtendedPublicLibraries: libedgetpu_dba.google.so
08-23 20:17:47.868 12588 12588 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-23 20:17:47.868 12588 12588 D nativeloader: InitVendorPublicLibraries: libOpenCL.so:libOpenCL-pixel.so:libedgetpu_client.google.so:libedgetpu_util.so:lib_aion_buffer.so:lib_jpg_encoder.so:libgxp.so
08-23 20:17:47.868 12588 12588 D nativeloader: InitProductPublicLibraries:
08-23 20:17:47.869 12588 12588 D nativeloader: Configuring clns-2 for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~Nj98FDzFGKab8q44iEjhpw==/app.passwordstore-9DuVAg9KTTFMzwf627ZrJA==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/app.passwordstore
08-23 20:17:47.869 12588 12588 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-23 20:17:47.875 12588 12588 D nativeloader: Configuring clns-3 for other apk /data/app/~~Nj98FDzFGKab8q44iEjhpw==/app.passwordstore-9DuVAg9KTTFMzwf627ZrJA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~Nj98FDzFGKab8q44iEjhpw==/app.passwordstore-9DuVAg9KTTFMzwf627ZrJA==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/app.passwordstore
08-23 20:17:47.878 12588 12588 D nativeloader: Load libframework-connectivity-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity.jar: ok
08-23 20:17:47.879 12588 12588 V GraphicsEnvironment: Currently set values for:
08-23 20:17:47.879 12588 12588 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[com.android.angle, com.linecorp.b612.android, com.campmobile.snow, com.google.android.apps.tachyon]
08-23 20:17:47.879 12588 12588 V GraphicsEnvironment:   angle_gl_driver_selection_values=[angle, native, native, native]
08-23 20:17:47.879 12588 12588 V GraphicsEnvironment: app.passwordstore is not listed in per-application setting
08-23 20:17:47.879 12588 12588 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
08-23 20:17:47.881 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10175; state: DISABLED
08-23 20:17:47.933 12588 12588 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
08-23 20:17:47.950 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 332679525; UID 10175; state: DISABLED
08-23 20:17:47.955 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10175; state: DISABLED
08-23 20:17:47.957 12588 12588 W libc    : Access denied finding property "ro.debuggable"
08-23 20:17:47.954 12588 12588 W p.passwordstore: type=1400 audit(0.0:3780): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=377 scontext=u:r:untrusted_app:s0:c175,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=app.passwordstore
08-23 20:17:47.972 12588 12620 E cutils-trace: Error opening trace file: No such file or directory (2)
08-23 20:17:47.983 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10175; state: ENABLED
08-23 20:17:47.983 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 63938206; UID 10175; state: DISABLED
08-23 20:17:47.992 12588 12588 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-23 20:17:47.992 12588 12588 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-23 20:17:48.030 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 303326708; UID 10175; state: DISABLED
08-23 20:17:48.555 12588 12588 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@27ed3c9
08-23 20:17:49.458 12588 12588 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
08-23 20:17:51.263 12588 12588 W RecyclerView: No adapter attached; skipping layout
08-23 20:17:51.271 12588 12588 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-23 20:17:51.271 12588 12588 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-23 20:17:51.295 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10175; state: ENABLED
08-23 20:17:51.307 12588 12609 W app.passwordstore: Cleared Reference was only reachable from finalizer (only reported once)
08-23 20:17:51.330 12588 12588 D CompatibilityChangeReporter: Compat change id reported: 163400105; UID 10175; state: ENABLED
08-23 20:17:51.332 12588 12588 I AssistStructure: Flattened final assist data: 4236 bytes, containing 2 windows, 30 views
08-23 20:17:51.495 12588 12588 D InsetsController: show(ime(), fromIme=true)
08-23 20:17:51.499 12588 12654 W InteractionJankMonitor: Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=app.passwordstore
08-23 20:17:51.518 12588 12588 W RecyclerView: No adapter attached; skipping layout
08-23 20:17:51.703 12588 12588 I ImeTracker: app.passwordstore:56245ed5: onShown
08-23 20:17:51.782 12588 12588 D VRI[PasswordStore]: visibilityChanged oldVisibility=true newVisibility=false
08-23 20:17:51.787 12588 12620 D HWUI    : endAllActiveAnimators on 0x400c8af995bfc00 (LayerDrawable) with handle 0x600c78303301f30
08-23 20:17:53.792 12588 12660 D ProfileInstaller: Skipping profile installation for app.passwordstore
08-23 20:18:02.859 12588 12588 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@209920448 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@3156342
08-23 20:18:02.860 12588 12588 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@b966eae
08-23 20:18:02.862 12588 12620 D HWUI    : endAllActiveAnimators on 0xf00c8af99668200 (RippleDrawable) with handle 0xe00c78303345a20
08-23 20:18:02.879 12588 12588 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-23 20:18:02.879 12588 12588 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-23 20:18:02.881 12588 12588 E DecryptActivity: NoKeysProvidedException
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at androidx.emoji2.text.MetadataRepo.access$decryptPgp-iWd_AH8(Unknown Source:365)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(Unknown Source:41)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:13)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
08-23 20:18:02.881 12588 12588 E DecryptActivity: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
08-23 20:18:02.884 12588 12588 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-23 20:18:02.884 12588 12588 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-23 20:18:02.931 12588 12588 W RecyclerView: No adapter attached; skipping layout
08-23 20:18:02.962 12588 12588 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 209920448
08-23 20:18:02.963 12588 12588 D InsetsController: hide(ime(), fromIme=true)
08-23 20:18:02.964 12588 12588 I ImeTracker: app.passwordstore:3128c9be: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
08-23 20:18:03.006 12588 12588 D InsetsController: show(ime(), fromIme=true)
08-23 20:18:03.025 12588 12588 W RecyclerView: No adapter attached; skipping layout
08-23 20:18:03.210 12588 12588 I ImeTracker: app.passwordstore:5dec871c: onShown
```

**Comment by msfjarvis** [comment]
Are you able to reproduce with a freshly generated key? If so, please attach it here so I include it in a regression test during debugging.

**Comment by Vintodrimmer** [comment]
This particular key was created using NitroKey, which I since lost, so I can't create another one the same way currently. I'll order a new one and try again, but that should take some time to arrive.

**Comment by msfjarvis** [comment]
Oh that explains it then, hardware keys are [currently unsupported](https://github.com/android-password-store/Android-Password-Store/issues/1486) in the development branch. Work [has been done](https://github.com/android-password-store/Android-Password-Store/pull/2170) to introduce this into APS but it's currently stalled due to lack of time on my end.

**Comment by Vintodrimmer** [comment]
I don't think it's hardware key issue, since I only used it to generate and then export the keys, which I then use as normal.
I think I found the issue, though. I have multiple keys that I export together by email instead of ID. If, instead, I only explicitly export the key mentioned in the `.gpg-id` then it works. So I assume it doesn't properly check the contents of `.gpg-id`?

**Comment by colonelpanic8** [comment]
@Vintodrimmer any progress here? I'm seeing the same thing

**Comment by colonelpanic8** [comment]
@Vintodrimmer is it prompting you for the password to unlock the key? In my case it seems to be doing so.

**Comment by msfjarvis** [comment]
Does someone have steps I can follow to generate a new key on my end that fails similarly so I can investigate this properly?

**Comment by msfjarvis** [comment]
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.
