### ISSUE TITLE
openkey chain error while create a new entry

### ISSUE THREAD

**Issue by jemyzhang** [zeapo/Android-Password-Store#369]
OpenKeychain: 4.8.1 (48002)
password store: Version: 1.2.0.73
One plus 3 Android Oreo

Error log:

```
01-05 20:52:33.113 30332 28153 E OpenPgp API: Exception in executeApi call

01-05 20:52:33.113 30332 28153 E OpenPgp API: android.os.DeadObjectException

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at android.os.BinderProxy.transactNative(Native Method)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at android.os.BinderProxy.transact(Binder.java:787)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at org.openintents.openpgp.IOpenPgpService2$Stub$Proxy.createOutputPipe(IOpenPgpService2.java:120)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at org.openintents.openpgp.util.OpenPgpApi.executeApi(OpenPgpApi.java:365)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at org.openintents.openpgp.util.OpenPgpApi.executeApi(OpenPgpApi.java:330)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.doInBackground(OpenPgpApi.java:301)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.doInBackground(OpenPgpApi.java:286)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

01-05 20:52:33.113 30332 28153 E OpenPgp API: 	at java.lang.Thread.run(Thread.java:764)

01-05 20:52:33.125 30332 30332 E PgpActivity: onError getErrorId:-1

01-05 20:52:33.125 30332 30332 E PgpActivity: onError getMessage:null
```

**Comment by jemyzhang** [comment]
I have to first import public key for encryption and then import private key for decryption, please correct me.
